reddit:
  user-agent: springboot:org.oauth2workshop:1.0.0 (by /u/Interesting_Ad_1019)
spring:
  security:
    oauth2:
      client:
        registration:
          reddit:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - identity
              - read
              - history
        provider:
          reddit:
            authorization-uri: https://www.reddit.com/api/v1/authorize
            token-uri: https://www.reddit.com/api/v1/access_token
            user-info-uri: https://oauth.reddit.com/api/v1/me
            user-name-attribute: 'name'
logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: debug